variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CONAN_USERNAME: "arsen-studio"
    CONAN_UPLOAD: "https://api.bintray.com/conan/arsen-studio/arsen-deps"

.build-template: &build-template
    before_script:
        - sudo pip install --upgrade conan_package_tools bincrafters_package_tools
        - conan user
    script:
        - python build.py
    only:
      - ci_tests
      - /^stable\/.+$/

gcc-4.9:
    image: lasote/conangcc49
    variables:
        CONAN_GCC_VERSIONS: "4.9"
    <<: *build-template

gcc-5:
    image: lasote/conangcc5
    variables:
        CONAN_GCC_VERSIONS: "5"
    <<: *build-template

gcc-6:
    image: lasote/conangcc6
    variables:
        CONAN_GCC_VERSIONS: "6"
    <<: *build-template

gcc-7:
    image: lasote/conangcc7
    variables:
        CONAN_GCC_VERSIONS: "7"
    <<: *build-template

gcc-8:
    image: lasote/conangcc8
    variables:
        CONAN_GCC_VERSIONS: "8"
    <<: *build-template

clang-4.0:
    image: lasote/conanclang40
    variables:
        CONAN_CLANG_VERSIONS: "4.0"
    <<: *build-template

clang-5.0:
    image: lasote/conanclang50
    variables:
        CONAN_CLANG_VERSIONS: "5.0"
    <<: *build-template

clang-6.0:
    image: lasote/conanclang60
    variables:
        CONAN_CLANG_VERSIONS: "6.0"
    <<: *build-template
