branches:
  only:
    - ci_tests
    - /^stable\/.+$/

build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    CONAN_UPLOAD: "https://api.bintray.com/conan/arsen-studio/arsen-deps"
    CONAN_USERNAME: "arsen-studio"
    
    matrix:
        - MINGW_CONFIGURATIONS: '4.9@x86_64@seh@posix, 4.9@x86@dwarf2@posix'
        - MINGW_CONFIGURATIONS: '4.9@x86_64@sjlj@posix, 4.9@x86@sjlj@posix'
        - MINGW_CONFIGURATIONS: '6@x86_64@seh@posix'
        - MINGW_CONFIGURATIONS: '7@x86_64@seh@posix'
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15


install:
  - git submodule update --init --recursive
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan conan_package_tools bincrafters_package_tools --upgrade
  - conan user # It creates the conan data directory

test_script:
  - python build.py
